
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    - name: Run FesadyabTests
      run: cd Fesadyab && mvn test -B -f pom.xml
    - name: Run Mizdooni
      run: cd Mizdooni && mvn test -B -f pom.xml
