name: Fesadyab Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Run Fesadyab test
        run: mvn -X clean test -f ./Fesadyab
      - name: Run Mizdooni test
        working-directory: Mizdooni
        run: mvn -X clean test -f ./Mizdooni
