name: Fesadyab Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build the project using Maven
      - name: Build with Maven
        run: |
          cd Fesadyab
          mvn clean install

      # Run tests
      - name: Run tests
        run: mvn test -f Fesadyab/pom.xml
