name: Fesadyab Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: maven

      - name: Run Mizdooni test
        working-directory: Mizdooni
        run: mvn -ntp -B -f test
      - name: Run Fesadyab test
        working-directory: Fesadyab
        run: mvn -ntp -B -f test
